CREATE TABLE IF NOT EXISTS `student`(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(12) NOT NULL,
    course VARCHAR(255) NOT NULL
);